// PokeDex Living Dex & Shiny Tracker Database
window.GAMES_DATABASE = {
  "Gen 1 (Kanto)": ["Red", "Blue", "Yellow", "FireRed", "LeafGreen", "Let's Go Pikachu", "Let's Go Eevee"],
  "Gen 2 (Johto)": ["Gold", "Silver", "Crystal", "HeartGold", "SoulSilver"],
  "Gen 3 (Hoenn)": ["Ruby", "Sapphire", "Emerald", "Omega Ruby", "Alpha Sapphire"],
  "Gen 4 (Sinnoh)": ["Diamond", "Pearl", "Platinum", "Brilliant Diamond", "Shining Pearl"],
  "Gen 5 (Unova)": ["Black", "White", "Black 2", "White 2"],
  "Gen 6 (Kalos)": ["X", "Y"],
  "Gen 7 (Alola)": ["Sun", "Moon", "Ultra Sun", "Ultra Moon"],
  "Gen 8 (Galar/Hisui)": ["Sword", "Shield", "Legends Arceus"],
  "Gen 9 (Paldea)": ["Scarlet", "Violet"],
  "Spinoffs & GO": ["Pokémon GO", "Pokémon HOME", "Pokémon Legends: Z-A"]
};

window.POKEBALLS = [
  "Poké Ball", "Great Ball", "Ultra Ball", "Master Ball", "Premier Ball",
  "Luxury Ball", "Fast Ball", "Level Ball", "Lure Ball", "Heavy Ball",
  "Love Ball", "Friend Ball", "Moon Ball", "Sport Ball", "Safari Ball",
  "Net Ball", "Nest Ball", "Repeat Ball", "Timer Ball", "Dive Ball",
  "Dusk Ball", "Heal Ball", "Quick Ball", "Cherish Ball", "Dream Ball",
  "Beast Ball", "Strange Ball", "Feather Ball", "Wing Ball", "Jet Ball",
  "Gigaton Ball", "Origin Ball"
];

window.NATURES = [
  "Adamant", "Bashful", "Bold", "Brave", "Calm", "Careful", "Docile",
  "Gentle", "Hardy", "Hasty", "Impish", "Jolly", "Lax", "Lonely",
  "Mild", "Modest", "Naive", "Naughty", "Quiet", "Quirky", "Rash",
  "Relaxed", "Sassy", "Serious", "Timid"
];

// Helper to determine Generation & Region by National Dex number
function getGenInfo(id) {
  if (id <= 151) return { gen: "Gen 1", region: "Kanto" };
  if (id <= 251) return { gen: "Gen 2", region: "Johto" };
  if (id <= 386) return { gen: "Gen 3", region: "Hoenn" };
  if (id <= 493) return { gen: "Gen 4", region: "Sinnoh" };
  if (id <= 649) return { gen: "Gen 5", region: "Unova" };
  if (id <= 721) return { gen: "Gen 6", region: "Kalos" };
  if (id <= 809) return { gen: "Gen 7", region: "Alola" };
  if (id <= 905) return { gen: "Gen 8", region: "Galar / Hisui" };
  return { gen: "Gen 9", region: "Paldea" };
}

// Famous Pokemon name map for high quality display
const KNOWN_POKEMON = {
  1: { name: "Bulbasaur", types: ["Grass", "Poison"] },
  2: { name: "Ivysaur", types: ["Grass", "Poison"] },
  3: { name: "Venusaur", types: ["Grass", "Poison"] },
  4: { name: "Charmander", types: ["Fire"] },
  5: { name: "Charmeleon", types: ["Fire"] },
  6: { name: "Charizard", types: ["Fire", "Flying"] },
  7: { name: "Squirtle", types: ["Water"] },
  8: { name: "Wartortle", types: ["Water"] },
  9: { name: "Blastoise", types: ["Water"] },
  10: { name: "Caterpie", types: ["Bug"] },
  11: { name: "Metapod", types: ["Bug"] },
  12: { name: "Butterfree", types: ["Bug", "Flying"] },
  13: { name: "Weedle", types: ["Bug", "Poison"] },
  14: { name: "Kakuna", types: ["Bug", "Poison"] },
  15: { name: "Beedrill", types: ["Bug", "Poison"] },
  16: { name: "Pidgey", types: ["Normal", "Flying"] },
  17: { name: "Pidgeotto", types: ["Normal", "Flying"] },
  18: { name: "Pidgeot", types: ["Normal", "Flying"] },
  19: { name: "Rattata", types: ["Normal"] },
  20: { name: "Raticate", types: ["Normal"] },
  21: { name: "Spearow", types: ["Normal", "Flying"] },
  22: { name: "Fearow", types: ["Normal", "Flying"] },
  23: { name: "Ekans", types: ["Poison"] },
  24: { name: "Arbok", types: ["Poison"] },
  25: { name: "Pikachu", types: ["Electric"] },
  26: { name: "Raichu", types: ["Electric"] },
  27: { name: "Sandshrew", types: ["Ground"] },
  28: { name: "Sandslash", types: ["Ground"] },
  29: { name: "Nidoran♀", types: ["Poison"] },
  30: { name: "Nidorina", types: ["Poison"] },
  31: { name: "Nidoqueen", types: ["Poison", "Ground"] },
  32: { name: "Nidoran♂", types: ["Poison"] },
  33: { name: "Nidorino", types: ["Poison"] },
  34: { name: "Nidoking", types: ["Poison", "Ground"] },
  35: { name: "Clefairy", types: ["Fairy"] },
  36: { name: "Clefable", types: ["Fairy"] },
  37: { name: "Vulpix", types: ["Fire"] },
  38: { name: "Ninetales", types: ["Fire"] },
  39: { name: "Jigglypuff", types: ["Normal", "Fairy"] },
  40: { name: "Wigglytuff", types: ["Normal", "Fairy"] },
  41: { name: "Zubat", types: ["Poison", "Flying"] },
  42: { name: "Golbat", types: ["Poison", "Flying"] },
  43: { name: "Oddish", types: ["Grass", "Poison"] },
  44: { name: "Gloom", types: ["Grass", "Poison"] },
  45: { name: "Vileplume", types: ["Grass", "Poison"] },
  46: { name: "Paras", types: ["Bug", "Grass"] },
  47: { name: "Parasect", types: ["Bug", "Grass"] },
  48: { name: "Venonat", types: ["Bug", "Poison"] },
  49: { name: "Venomoth", types: ["Bug", "Poison"] },
  50: { name: "Diglett", types: ["Ground"] },
  51: { name: "Dugtrio", types: ["Ground"] },
  52: { name: "Meowth", types: ["Normal"] },
  53: { name: "Persian", types: ["Normal"] },
  54: { name: "Psyduck", types: ["Water"] },
  55: { name: "Golduck", types: ["Water"] },
  56: { name: "Mankey", types: ["Fighting"] },
  57: { name: "Primeape", types: ["Fighting"] },
  58: { name: "Growlithe", types: ["Fire"] },
  59: { name: "Arcanine", types: ["Fire"] },
  60: { name: "Poliwag", types: ["Water"] },
  61: { name: "Poliwhirl", types: ["Water"] },
  62: { name: "Poliwrath", types: ["Water", "Fighting"] },
  63: { name: "Abra", types: ["Psychic"] },
  64: { name: "Kadabra", types: ["Psychic"] },
  65: { name: "Alakazam", types: ["Psychic"] },
  66: { name: "Machop", types: ["Fighting"] },
  67: { name: "Machoke", types: ["Fighting"] },
  68: { name: "Machamp", types: ["Fighting"] },
  69: { name: "Bellsprout", types: ["Grass", "Poison"] },
  70: { name: "Weepinbell", types: ["Grass", "Poison"] },
  71: { name: "Victreebel", types: ["Grass", "Poison"] },
  72: { name: "Tentacool", types: ["Water", "Poison"] },
  73: { name: "Tentacruel", types: ["Water", "Poison"] },
  74: { name: "Geodude", types: ["Rock", "Ground"] },
  75: { name: "Graveler", types: ["Rock", "Ground"] },
  76: { name: "Golem", types: ["Rock", "Ground"] },
  77: { name: "Ponyta", types: ["Fire"] },
  78: { name: "Rapidash", types: ["Fire"] },
  79: { name: "Slowpoke", types: ["Water", "Psychic"] },
  80: { name: "Slowbro", types: ["Water", "Psychic"] },
  81: { name: "Magnemite", types: ["Electric", "Steel"] },
  82: { name: "Magneton", types: ["Electric", "Steel"] },
  83: { name: "Farfetch’d", types: ["Normal", "Flying"] },
  84: { name: "Doduo", types: ["Normal", "Flying"] },
  85: { name: "Dodrio", types: ["Normal", "Flying"] },
  86: { name: "Seel", types: ["Water"] },
  87: { name: "Dewgong", types: ["Water", "Ice"] },
  88: { name: "Grimer", types: ["Poison"] },
  89: { name: "Muk", types: ["Poison"] },
  90: { name: "Shellder", types: ["Water"] },
  91: { name: "Cloyster", types: ["Water", "Ice"] },
  92: { name: "Gastly", types: ["Ghost", "Poison"] },
  93: { name: "Haunter", types: ["Ghost", "Poison"] },
  94: { name: "Gengar", types: ["Ghost", "Poison"] },
  95: { name: "Onix", types: ["Rock", "Ground"] },
  96: { name: "Drowzee", types: ["Psychic"] },
  97: { name: "Hypno", types: ["Psychic"] },
  98: { name: "Krabby", types: ["Water"] },
  99: { name: "Kingler", types: ["Water"] },
  100: { name: "Voltorb", types: ["Electric"] },
  101: { name: "Electrode", types: ["Electric"] },
  102: { name: "Exeggcute", types: ["Grass", "Psychic"] },
  103: { name: "Exeggutor", types: ["Grass", "Psychic"] },
  104: { name: "Cubone", types: ["Ground"] },
  105: { name: "Marowak", types: ["Ground"] },
  106: { name: "Hitmonlee", types: ["Fighting"] },
  107: { name: "Hitmonchan", types: ["Fighting"] },
  108: { name: "Lickitung", types: ["Normal"] },
  109: { name: "Koffing", types: ["Poison"] },
  110: { name: "Weezing", types: ["Poison"] },
  111: { name: "Rhyhorn", types: ["Ground", "Rock"] },
  112: { name: "Rhydon", types: ["Ground", "Rock"] },
  113: { name: "Chansey", types: ["Normal"] },
  114: { name: "Tangela", types: ["Grass"] },
  115: { name: "Kangaskhan", types: ["Normal"] },
  116: { name: "Horsea", types: ["Water"] },
  117: { name: "Seadra", types: ["Water"] },
  118: { name: "Goldeen", types: ["Water"] },
  119: { name: "Seaking", types: ["Water"] },
  120: { name: "Staryu", types: ["Water"] },
  121: { name: "Starmie", types: ["Water", "Psychic"] },
  122: { name: "Mr. Mime", types: ["Psychic", "Fairy"] },
  123: { name: "Scyther", types: ["Bug", "Flying"] },
  124: { name: "Jynx", types: ["Ice", "Psychic"] },
  125: { name: "Electabuzz", types: ["Electric"] },
  126: { name: "Magmar", types: ["Fire"] },
  127: { name: "Pinsir", types: ["Bug"] },
  128: { name: "Tauros", types: ["Normal"] },
  129: { name: "Magikarp", types: ["Water"] },
  130: { name: "Gyarados", types: ["Water", "Flying"] },
  131: { name: "Lapras", types: ["Water", "Ice"] },
  132: { name: "Ditto", types: ["Normal"] },
  133: { name: "Eevee", types: ["Normal"] },
  134: { name: "Vaporeon", types: ["Water"] },
  135: { name: "Jolteon", types: ["Electric"] },
  136: { name: "Flareon", types: ["Fire"] },
  137: { name: "Porygon", types: ["Normal"] },
  138: { name: "Omanyte", types: ["Rock", "Water"] },
  139: { name: "Omastar", types: ["Rock", "Water"] },
  140: { name: "Kabuto", types: ["Rock", "Water"] },
  141: { name: "Kabutops", types: ["Rock", "Water"] },
  142: { name: "Aerodactyl", types: ["Rock", "Flying"] },
  143: { name: "Snorlax", types: ["Normal"] },
  144: { name: "Articuno", types: ["Ice", "Flying"] },
  145: { name: "Zapdos", types: ["Electric", "Flying"] },
  146: { name: "Moltres", types: ["Fire", "Flying"] },
  147: { name: "Dratini", types: ["Dragon"] },
  148: { name: "Dragonair", types: ["Dragon"] },
  149: { name: "Dragonite", types: ["Dragon", "Flying"] },
  150: { name: "Mewtwo", types: ["Psychic"] },
  151: { name: "Mew", types: ["Psychic"] },
  152: { name: "Chikorita", types: ["Grass"] },
  153: { name: "Bayleef", types: ["Grass"] },
  154: { name: "Meganium", types: ["Grass"] },
  155: { name: "Cyndaquil", types: ["Fire"] },
  156: { name: "Quilava", types: ["Fire"] },
  157: { name: "Typhlosion", types: ["Fire"] },
  158: { name: "Totodile", types: ["Water"] },
  159: { name: "Croconaw", types: ["Water"] },
  160: { name: "Feraligatr", types: ["Water"] },
  161: { name: "Sentret", types: ["Normal"] },
  162: { name: "Furret", types: ["Normal"] },
  163: { name: "Hoothoot", types: ["Normal", "Flying"] },
  164: { name: "Noctowl", types: ["Normal", "Flying"] },
  165: { name: "Ledyba", types: ["Bug", "Flying"] },
  166: { name: "Ledian", types: ["Bug", "Flying"] },
  167: { name: "Spinarak", types: ["Bug", "Poison"] },
  168: { name: "Ariados", types: ["Bug", "Poison"] },
  169: { name: "Crobat", types: ["Poison", "Flying"] },
  170: { name: "Chinchou", types: ["Water", "Electric"] },
  171: { name: "Lanturn", types: ["Water", "Electric"] },
  172: { name: "Pichu", types: ["Electric"] },
  173: { name: "Cleffa", types: ["Fairy"] },
  174: { name: "Igglybuff", types: ["Normal", "Fairy"] },
  175: { name: "Togepi", types: ["Fairy"] },
  176: { name: "Togetic", types: ["Fairy", "Flying"] },
  177: { name: "Natu", types: ["Psychic", "Flying"] },
  178: { name: "Xatu", types: ["Psychic", "Flying"] },
  179: { name: "Mareep", types: ["Electric"] },
  180: { name: "Flaaffy", types: ["Electric"] },
  181: { name: "Ampharos", types: ["Electric"] },
  182: { name: "Bellossom", types: ["Grass"] },
  183: { name: "Marill", types: ["Water", "Fairy"] },
  184: { name: "Azumarill", types: ["Water", "Fairy"] },
  185: { name: "Sudowoodo", types: ["Rock"] },
  186: { name: "Politoed", types: ["Water"] },
  187: { name: "Hoppip", types: ["Grass", "Flying"] },
  188: { name: "Skiploom", types: ["Grass", "Flying"] },
  189: { name: "Jumpluff", types: ["Grass", "Flying"] },
  190: { name: "Aipom", types: ["Normal"] },
  191: { name: "Sunkern", types: ["Grass"] },
  192: { name: "Sunflora", types: ["Grass"] },
  193: { name: "Yanma", types: ["Bug", "Flying"] },
  194: { name: "Wooper", types: ["Water", "Ground"] },
  195: { name: "Quagsire", types: ["Water", "Ground"] },
  196: { name: "Espeon", types: ["Psychic"] },
  197: { name: "Umbreon", types: ["Dark"] },
  198: { name: "Murkrow", types: ["Dark", "Flying"] },
  199: { name: "Slowking", types: ["Water", "Psychic"] },
  200: { name: "Misdreavus", types: ["Ghost"] },
  201: { name: "Unown", types: ["Psychic"] },
  202: { name: "Wobbuffet", types: ["Psychic"] },
  203: { name: "Girafarig", types: ["Normal", "Psychic"] },
  204: { name: "Pineco", types: ["Bug"] },
  205: { name: "Forretress", types: ["Bug", "Steel"] },
  206: { name: "Dunsparce", types: ["Normal"] },
  207: { name: "Gligar", types: ["Ground", "Flying"] },
  208: { name: "Steelix", types: ["Steel", "Ground"] },
  209: { name: "Snubbull", types: ["Fairy"] },
  210: { name: "Granbull", types: ["Fairy"] },
  211: { name: "Qwilfish", types: ["Water", "Poison"] },
  212: { name: "Scizor", types: ["Bug", "Steel"] },
  213: { name: "Shuckle", types: ["Bug", "Rock"] },
  214: { name: "Heracross", types: ["Bug", "Fighting"] },
  215: { name: "Sneasel", types: ["Dark", "Ice"] },
  216: { name: "Teddiursa", types: ["Normal"] },
  217: { name: "Ursaring", types: ["Normal"] },
  218: { name: "Slugma", types: ["Fire"] },
  219: { name: "Magcargo", types: ["Fire", "Rock"] },
  220: { name: "Swinub", types: ["Ice", "Ground"] },
  221: { name: "Piloswine", types: ["Ice", "Ground"] },
  222: { name: "Corsola", types: ["Water", "Rock"] },
  223: { name: "Remoraid", types: ["Water"] },
  224: { name: "Octillery", types: ["Water"] },
  225: { name: "Delibird", types: ["Ice", "Flying"] },
  226: { name: "Mantine", types: ["Water", "Flying"] },
  227: { name: "Skarmory", types: ["Steel", "Flying"] },
  228: { name: "Houndour", types: ["Dark", "Fire"] },
  229: { name: "Houndoom", types: ["Dark", "Fire"] },
  230: { name: "Kingdra", types: ["Water", "Dragon"] },
  231: { name: "Phanpy", types: ["Ground"] },
  232: { name: "Donphan", types: ["Ground"] },
  233: { name: "Porygon2", types: ["Normal"] },
  234: { name: "Stantler", types: ["Normal"] },
  235: { name: "Smeargle", types: ["Normal"] },
  236: { name: "Tyrogue", types: ["Fighting"] },
  237: { name: "Hitmontop", types: ["Fighting"] },
  238: { name: "Smoochum", types: ["Ice", "Psychic"] },
  239: { name: "Elekid", types: ["Electric"] },
  240: { name: "Magby", types: ["Fire"] },
  241: { name: "Miltank", types: ["Normal"] },
  242: { name: "Blissey", types: ["Normal"] },
  243: { name: "Raikou", types: ["Electric"] },
  244: { name: "Entei", types: ["Fire"] },
  245: { name: "Suicune", types: ["Water"] },
  246: { name: "Larvitar", types: ["Rock", "Ground"] },
  247: { name: "Pupitar", types: ["Rock", "Ground"] },
  248: { name: "Tyranitar", types: ["Rock", "Dark"] },
  249: { name: "Lugia", types: ["Psychic", "Flying"] },
  250: { name: "Ho-Oh", types: ["Fire", "Flying"] },
  251: { name: "Celebi", types: ["Psychic", "Grass"] },
  252: { name: "Treecko", types: ["Grass"] },
  253: { name: "Grovyle", types: ["Grass"] },
  254: { name: "Sceptile", types: ["Grass"] },
  255: { name: "Torchic", types: ["Fire"] },
  256: { name: "Combusken", types: ["Fire", "Fighting"] },
  257: { name: "Blaziken", types: ["Fire", "Fighting"] },
  258: { name: "Mudkip", types: ["Water"] },
  259: { name: "Marshtomp", types: ["Water", "Ground"] },
  260: { name: "Swampert", types: ["Water", "Ground"] },
  261: { name: "Poochyena", types: ["Dark"] },
  262: { name: "Mightyena", types: ["Dark"] },
  263: { name: "Zigzagoon", types: ["Normal"] },
  264: { name: "Linoone", types: ["Normal"] },
  265: { name: "Wurmple", types: ["Bug"] },
  266: { name: "Silcoon", types: ["Bug"] },
  267: { name: "Beautifly", types: ["Bug", "Flying"] },
  268: { name: "Cascoon", types: ["Bug"] },
  269: { name: "Dustox", types: ["Bug", "Poison"] },
  270: { name: "Lotad", types: ["Water", "Grass"] },
  271: { name: "Lombre", types: ["Water", "Grass"] },
  272: { name: "Ludicolo", types: ["Water", "Grass"] },
  273: { name: "Seedot", types: ["Grass"] },
  274: { name: "Nuzleaf", types: ["Grass", "Dark"] },
  275: { name: "Shiftry", types: ["Grass", "Dark"] },
  276: { name: "Taillow", types: ["Normal", "Flying"] },
  277: { name: "Swellow", types: ["Normal", "Flying"] },
  278: { name: "Wingull", types: ["Water", "Flying"] },
  279: { name: "Pelipper", types: ["Water", "Flying"] },
  280: { name: "Ralts", types: ["Psychic", "Fairy"] },
  281: { name: "Kirlia", types: ["Psychic", "Fairy"] },
  282: { name: "Gardevoir", types: ["Psychic", "Fairy"] },
  283: { name: "Surskit", types: ["Bug", "Water"] },
  284: { name: "Masquerain", types: ["Bug", "Flying"] },
  285: { name: "Shroomish", types: ["Grass"] },
  286: { name: "Breloom", types: ["Grass", "Fighting"] },
  287: { name: "Slakoth", types: ["Normal"] },
  288: { name: "Vigoroth", types: ["Normal"] },
  289: { name: "Slaking", types: ["Normal"] },
  290: { name: "Nincada", types: ["Bug", "Ground"] },
  291: { name: "Ninjask", types: ["Bug", "Flying"] },
  292: { name: "Shedinja", types: ["Bug", "Ghost"] },
  293: { name: "Whismur", types: ["Normal"] },
  294: { name: "Loudred", types: ["Normal"] },
  295: { name: "Exploud", types: ["Normal"] },
  296: { name: "Makuhita", types: ["Fighting"] },
  297: { name: "Hariyama", types: ["Fighting"] },
  298: { name: "Azurill", types: ["Normal", "Fairy"] },
  299: { name: "Nosepass", types: ["Rock"] },
  300: { name: "Skitty", types: ["Normal"] },
  301: { name: "Delcatty", types: ["Normal"] },
  302: { name: "Sableye", types: ["Dark", "Ghost"] },
  303: { name: "Mawile", types: ["Steel", "Fairy"] },
  304: { name: "Aron", types: ["Steel", "Rock"] },
  305: { name: "Lairon", types: ["Steel", "Rock"] },
  306: { name: "Aggron", types: ["Steel", "Rock"] },
  307: { name: "Meditite", types: ["Fighting", "Psychic"] },
  308: { name: "Medicham", types: ["Fighting", "Psychic"] },
  309: { name: "Electrike", types: ["Electric"] },
  310: { name: "Manectric", types: ["Electric"] },
  311: { name: "Plusle", types: ["Electric"] },
  312: { name: "Minun", types: ["Electric"] },
  313: { name: "Volbeat", types: ["Bug"] },
  314: { name: "Illumise", types: ["Bug"] },
  315: { name: "Roselia", types: ["Grass", "Poison"] },
  316: { name: "Gulpin", types: ["Poison"] },
  317: { name: "Swalot", types: ["Poison"] },
  318: { name: "Carvanha", types: ["Water", "Dark"] },
  319: { name: "Sharpedo", types: ["Water", "Dark"] },
  320: { name: "Wailmer", types: ["Water"] },
  321: { name: "Wailord", types: ["Water"] },
  322: { name: "Numel", types: ["Fire", "Ground"] },
  323: { name: "Camerupt", types: ["Fire", "Ground"] },
  324: { name: "Torkoal", types: ["Fire"] },
  325: { name: "Spoink", types: ["Psychic"] },
  326: { name: "Grumpig", types: ["Psychic"] },
  327: { name: "Spinda", types: ["Normal"] },
  328: { name: "Trapinch", types: ["Ground"] },
  329: { name: "Vibrava", types: ["Ground", "Dragon"] },
  330: { name: "Flygon", types: ["Ground", "Dragon"] },
  331: { name: "Cacnea", types: ["Grass"] },
  332: { name: "Cacturne", types: ["Grass", "Dark"] },
  333: { name: "Swablu", types: ["Normal", "Flying"] },
  334: { name: "Altaria", types: ["Dragon", "Flying"] },
  335: { name: "Zangoose", types: ["Normal"] },
  336: { name: "Seviper", types: ["Poison"] },
  337: { name: "Lunatone", types: ["Rock", "Psychic"] },
  338: { name: "Solrock", types: ["Rock", "Psychic"] },
  339: { name: "Barboach", types: ["Water", "Ground"] },
  340: { name: "Whiscash", types: ["Water", "Ground"] },
  341: { name: "Corphish", types: ["Water"] },
  342: { name: "Crawdaunt", types: ["Water", "Dark"] },
  343: { name: "Baltoy", types: ["Ground", "Psychic"] },
  344: { name: "Claydol", types: ["Ground", "Psychic"] },
  345: { name: "Lileep", types: ["Rock", "Grass"] },
  346: { name: "Cradily", types: ["Rock", "Grass"] },
  347: { name: "Anorith", types: ["Rock", "Bug"] },
  348: { name: "Armaldo", types: ["Rock", "Bug"] },
  349: { name: "Feebas", types: ["Water"] },
  350: { name: "Milotic", types: ["Water"] },
  351: { name: "Castform", types: ["Normal"] },
  352: { name: "Kecleon", types: ["Normal"] },
  353: { name: "Shuppet", types: ["Ghost"] },
  354: { name: "Banette", types: ["Ghost"] },
  355: { name: "Duskull", types: ["Ghost"] },
  356: { name: "Dusclops", types: ["Ghost"] },
  357: { name: "Tropius", types: ["Grass", "Flying"] },
  358: { name: "Chimecho", types: ["Psychic"] },
  359: { name: "Absol", types: ["Dark"] },
  360: { name: "Wynaut", types: ["Psychic"] },
  361: { name: "Snorunt", types: ["Ice"] },
  362: { name: "Glalie", types: ["Ice"] },
  363: { name: "Spheal", types: ["Ice", "Water"] },
  364: { name: "Sealeo", types: ["Ice", "Water"] },
  365: { name: "Walrein", types: ["Ice", "Water"] },
  366: { name: "Clamperl", types: ["Water"] },
  367: { name: "Huntail", types: ["Water"] },
  368: { name: "Gorebyss", types: ["Water"] },
  369: { name: "Relicanth", types: ["Water", "Rock"] },
  370: { name: "Luvdisc", types: ["Water"] },
  371: { name: "Bagon", types: ["Dragon"] },
  372: { name: "Shelgon", types: ["Dragon"] },
  373: { name: "Salamence", types: ["Dragon", "Flying"] },
  374: { name: "Beldum", types: ["Steel", "Psychic"] },
  375: { name: "Metang", types: ["Steel", "Psychic"] },
  376: { name: "Metagross", types: ["Steel", "Psychic"] },
  377: { name: "Regirock", types: ["Rock"] },
  378: { name: "Regice", types: ["Ice"] },
  379: { name: "Registeel", types: ["Steel"] },
  380: { name: "Latias", types: ["Dragon", "Psychic"] },
  381: { name: "Latios", types: ["Dragon", "Psychic"] },
  382: { name: "Kyogre", types: ["Water"] },
  383: { name: "Groudon", types: ["Ground"] },
  384: { name: "Rayquaza", types: ["Dragon", "Flying"] },
  385: { name: "Jirachi", types: ["Steel", "Psychic"] },
  386: { name: "Deoxys", types: ["Psychic"] },
  387: { name: "Turtwig", types: ["Grass"] },
  388: { name: "Grotle", types: ["Grass"] },
  389: { name: "Torterra", types: ["Grass", "Ground"] },
  390: { name: "Chimchar", types: ["Fire"] },
  391: { name: "Monferno", types: ["Fire", "Fighting"] },
  392: { name: "Infernape", types: ["Fire", "Fighting"] },
  393: { name: "Piplup", types: ["Water"] },
  394: { name: "Prinplup", types: ["Water"] },
  395: { name: "Empoleon", types: ["Water", "Steel"] },
  396: { name: "Starly", types: ["Normal", "Flying"] },
  397: { name: "Staravia", types: ["Normal", "Flying"] },
  398: { name: "Staraptor", types: ["Normal", "Flying"] },
  399: { name: "Bidoof", types: ["Normal"] },
  400: { name: "Bibarel", types: ["Normal", "Water"] },
  401: { name: "Kricketot", types: ["Bug"] },
  402: { name: "Kricketune", types: ["Bug"] },
  403: { name: "Shinx", types: ["Electric"] },
  404: { name: "Luxio", types: ["Electric"] },
  405: { name: "Luxray", types: ["Electric"] },
  406: { name: "Budew", types: ["Grass", "Poison"] },
  407: { name: "Roserade", types: ["Grass", "Poison"] },
  408: { name: "Cranidos", types: ["Rock"] },
  409: { name: "Rampardos", types: ["Rock"] },
  410: { name: "Shieldon", types: ["Rock", "Steel"] },
  411: { name: "Bastiodon", types: ["Rock", "Steel"] },
  412: { name: "Burmy", types: ["Bug"] },
  413: { name: "Wormadam", types: ["Bug", "Grass"] },
  414: { name: "Mothim", types: ["Bug", "Flying"] },
  415: { name: "Combee", types: ["Bug", "Flying"] },
  416: { name: "Vespiquen", types: ["Bug", "Flying"] },
  417: { name: "Pachirisu", types: ["Electric"] },
  418: { name: "Buizel", types: ["Water"] },
  419: { name: "Floatzel", types: ["Water"] },
  420: { name: "Cherubi", types: ["Grass"] },
  421: { name: "Cherrim", types: ["Grass"] },
  422: { name: "Shellos", types: ["Water"] },
  423: { name: "Gastrodon", types: ["Water", "Ground"] },
  424: { name: "Ambipom", types: ["Normal"] },
  425: { name: "Drifloon", types: ["Ghost", "Flying"] },
  426: { name: "Drifblim", types: ["Ghost", "Flying"] },
  427: { name: "Buneary", types: ["Normal"] },
  428: { name: "Lopunny", types: ["Normal"] },
  429: { name: "Mismagius", types: ["Ghost"] },
  430: { name: "Honchkrow", types: ["Dark", "Flying"] },
  431: { name: "Glameow", types: ["Normal"] },
  432: { name: "Purugly", types: ["Normal"] },
  433: { name: "Chingling", types: ["Psychic"] },
  434: { name: "Stunky", types: ["Poison", "Dark"] },
  435: { name: "Skuntank", types: ["Poison", "Dark"] },
  436: { name: "Bronzor", types: ["Steel", "Psychic"] },
  437: { name: "Bronzong", types: ["Steel", "Psychic"] },
  438: { name: "Bonsly", types: ["Rock"] },
  439: { name: "Mime Jr.", types: ["Psychic", "Fairy"] },
  440: { name: "Happiny", types: ["Normal"] },
  441: { name: "Chatot", types: ["Normal", "Flying"] },
  442: { name: "Spiritomb", types: ["Ghost", "Dark"] },
  443: { name: "Gible", types: ["Dragon", "Ground"] },
  444: { name: "Gabite", types: ["Dragon", "Ground"] },
  445: { name: "Garchomp", types: ["Dragon", "Ground"] },
  446: { name: "Munchlax", types: ["Normal"] },
  447: { name: "Riolu", types: ["Fighting"] },
  448: { name: "Lucario", types: ["Fighting", "Steel"] },
  449: { name: "Hippopotas", types: ["Ground"] },
  450: { name: "Hippowdon", types: ["Ground"] },
  451: { name: "Skorupi", types: ["Poison", "Bug"] },
  452: { name: "Drapion", types: ["Poison", "Dark"] },
  453: { name: "Croagunk", types: ["Poison", "Fighting"] },
  454: { name: "Toxicroak", types: ["Poison", "Fighting"] },
  455: { name: "Carnivine", types: ["Grass"] },
  456: { name: "Finneon", types: ["Water"] },
  457: { name: "Lumineon", types: ["Water"] },
  458: { name: "Mantyke", types: ["Water", "Flying"] },
  459: { name: "Snover", types: ["Grass", "Ice"] },
  460: { name: "Abomasnow", types: ["Grass", "Ice"] },
  461: { name: "Weavile", types: ["Dark", "Ice"] },
  462: { name: "Magnezone", types: ["Electric", "Steel"] },
  463: { name: "Lickilicky", types: ["Normal"] },
  464: { name: "Rhyperior", types: ["Ground", "Rock"] },
  465: { name: "Tangrowth", types: ["Grass"] },
  466: { name: "Electivire", types: ["Electric"] },
  467: { name: "Magmortar", types: ["Fire"] },
  468: { name: "Togekiss", types: ["Fairy", "Flying"] },
  469: { name: "Yanmega", types: ["Bug", "Flying"] },
  470: { name: "Leafeon", types: ["Grass"] },
  471: { name: "Glaceon", types: ["Ice"] },
  472: { name: "Gliscor", types: ["Ground", "Flying"] },
  473: { name: "Mamoswine", types: ["Ice", "Ground"] },
  474: { name: "Porygon-Z", types: ["Normal"] },
  475: { name: "Gallade", types: ["Psychic", "Fighting"] },
  476: { name: "Probopass", types: ["Rock", "Steel"] },
  477: { name: "Dusknoir", types: ["Ghost"] },
  478: { name: "Froslass", types: ["Ice", "Ghost"] },
  479: { name: "Rotom", types: ["Electric", "Ghost"] },
  480: { name: "Uxie", types: ["Psychic"] },
  481: { name: "Mesprit", types: ["Psychic"] },
  482: { name: "Azelf", types: ["Psychic"] },
  483: { name: "Dialga", types: ["Steel", "Dragon"] },
  484: { name: "Palkia", types: ["Water", "Dragon"] },
  485: { name: "Heatran", types: ["Fire", "Steel"] },
  486: { name: "Regigigas", types: ["Normal"] },
  487: { name: "Giratina", types: ["Ghost", "Dragon"] },
  488: { name: "Cresselia", types: ["Psychic"] },
  489: { name: "Phione", types: ["Water"] },
  490: { name: "Manaphy", types: ["Water"] },
  491: { name: "Darkrai", types: ["Dark"] },
  492: { name: "Shaymin", types: ["Grass"] },
  493: { name: "Arceus", types: ["Normal"] },
  494: { name: "Victini", types: ["Psychic", "Fire"] },
  495: { name: "Snivy", types: ["Grass"] },
  496: { name: "Servine", types: ["Grass"] },
  497: { name: "Serperior", types: ["Grass"] },
  498: { name: "Tepig", types: ["Fire"] },
  499: { name: "Pignite", types: ["Fire", "Fighting"] },
  500: { name: "Emboar", types: ["Fire", "Fighting"] },
  501: { name: "Oshawott", types: ["Water"] },
  502: { name: "Dewott", types: ["Water"] },
  503: { name: "Samurott", types: ["Water"] },
  504: { name: "Patrat", types: ["Normal"] },
  505: { name: "Watchog", types: ["Normal"] },
  506: { name: "Lillipup", types: ["Normal"] },
  507: { name: "Herdier", types: ["Normal"] },
  508: { name: "Stoutland", types: ["Normal"] },
  509: { name: "Purrloin", types: ["Dark"] },
  510: { name: "Liepard", types: ["Dark"] },
  511: { name: "Pansage", types: ["Grass"] },
  512: { name: "Simisage", types: ["Grass"] },
  513: { name: "Pansear", types: ["Fire"] },
  514: { name: "Simisear", types: ["Fire"] },
  515: { name: "Panpour", types: ["Water"] },
  516: { name: "Simipour", types: ["Water"] },
  517: { name: "Munna", types: ["Psychic"] },
  518: { name: "Musharna", types: ["Psychic"] },
  519: { name: "Pidove", types: ["Normal", "Flying"] },
  520: { name: "Tranquill", types: ["Normal", "Flying"] },
  521: { name: "Unfezant", types: ["Normal", "Flying"] },
  522: { name: "Blitzle", types: ["Electric"] },
  523: { name: "Zebstrika", types: ["Electric"] },
  524: { name: "Roggenrola", types: ["Rock"] },
  525: { name: "Boldore", types: ["Rock"] },
  526: { name: "Gigalith", types: ["Rock"] },
  527: { name: "Woobat", types: ["Psychic", "Flying"] },
  528: { name: "Swoobat", types: ["Psychic", "Flying"] },
  529: { name: "Drilbur", types: ["Ground"] },
  530: { name: "Excadrill", types: ["Ground", "Steel"] },
  531: { name: "Audino", types: ["Normal"] },
  532: { name: "Timburr", types: ["Fighting"] },
  533: { name: "Gurdurr", types: ["Fighting"] },
  534: { name: "Conkeldurr", types: ["Fighting"] },
  535: { name: "Tympole", types: ["Water"] },
  536: { name: "Palpitoad", types: ["Water", "Ground"] },
  537: { name: "Seismitoad", types: ["Water", "Ground"] },
  538: { name: "Throh", types: ["Fighting"] },
  539: { name: "Sawk", types: ["Fighting"] },
  540: { name: "Sewaddle", types: ["Bug", "Grass"] },
  541: { name: "Swadloon", types: ["Bug", "Grass"] },
  542: { name: "Leavanny", types: ["Bug", "Grass"] },
  543: { name: "Venipede", types: ["Bug", "Poison"] },
  544: { name: "Whirlipede", types: ["Bug", "Poison"] },
  545: { name: "Scolipede", types: ["Bug", "Poison"] },
  546: { name: "Cottonee", types: ["Grass", "Fairy"] },
  547: { name: "Whimsicott", types: ["Grass", "Fairy"] },
  548: { name: "Petilil", types: ["Grass"] },
  549: { name: "Lilligant", types: ["Grass"] },
  550: { name: "Basculin", types: ["Water"] },
  551: { name: "Sandile", types: ["Ground", "Dark"] },
  552: { name: "Krokorok", types: ["Ground", "Dark"] },
  553: { name: "Krookodile", types: ["Ground", "Dark"] },
  554: { name: "Darumaka", types: ["Fire"] },
  555: { name: "Darmanitan", types: ["Fire"] },
  556: { name: "Maractus", types: ["Grass"] },
  557: { name: "Dwebble", types: ["Bug", "Rock"] },
  558: { name: "Crustle", types: ["Bug", "Rock"] },
  559: { name: "Scraggy", types: ["Dark", "Fighting"] },
  560: { name: "Scrafty", types: ["Dark", "Fighting"] },
  561: { name: "Sigilyph", types: ["Psychic", "Flying"] },
  562: { name: "Yamask", types: ["Ghost"] },
  563: { name: "Cofagrigus", types: ["Ghost"] },
  564: { name: "Tirtouga", types: ["Water", "Rock"] },
  565: { name: "Carracosta", types: ["Water", "Rock"] },
  566: { name: "Archen", types: ["Rock", "Flying"] },
  567: { name: "Archeops", types: ["Rock", "Flying"] },
  568: { name: "Trubbish", types: ["Poison"] },
  569: { name: "Garbodor", types: ["Poison"] },
  570: { name: "Zorua", types: ["Dark"] },
  571: { name: "Zoroark", types: ["Dark"] },
  572: { name: "Minccino", types: ["Normal"] },
  573: { name: "Cinccino", types: ["Normal"] },
  574: { name: "Gothita", types: ["Psychic"] },
  575: { name: "Gothorita", types: ["Psychic"] },
  576: { name: "Gothitelle", types: ["Psychic"] },
  577: { name: "Solosis", types: ["Psychic"] },
  578: { name: "Duosion", types: ["Psychic"] },
  579: { name: "Reuniclus", types: ["Psychic"] },
  580: { name: "Ducklett", types: ["Water", "Flying"] },
  581: { name: "Swanna", types: ["Water", "Flying"] },
  582: { name: "Vanillite", types: ["Ice"] },
  583: { name: "Vanillish", types: ["Ice"] },
  584: { name: "Vanilluxe", types: ["Ice"] },
  585: { name: "Deerling", types: ["Normal", "Grass"] },
  586: { name: "Sawsbuck", types: ["Normal", "Grass"] },
  587: { name: "Emolga", types: ["Electric", "Flying"] },
  588: { name: "Karrablast", types: ["Bug"] },
  589: { name: "Escavalier", types: ["Bug", "Steel"] },
  590: { name: "Foongus", types: ["Grass", "Poison"] },
  591: { name: "Amoonguss", types: ["Grass", "Poison"] },
  592: { name: "Frillish", types: ["Water", "Ghost"] },
  593: { name: "Jellicent", types: ["Water", "Ghost"] },
  594: { name: "Alomomola", types: ["Water"] },
  595: { name: "Joltik", types: ["Bug", "Electric"] },
  596: { name: "Galvantula", types: ["Bug", "Electric"] },
  597: { name: "Ferroseed", types: ["Grass", "Steel"] },
  598: { name: "Ferrothorn", types: ["Grass", "Steel"] },
  599: { name: "Klink", types: ["Steel"] },
  600: { name: "Klang", types: ["Steel"] },
  601: { name: "Klinklang", types: ["Steel"] },
  602: { name: "Tynamo", types: ["Electric"] },
  603: { name: "Eelektrik", types: ["Electric"] },
  604: { name: "Eelektross", types: ["Electric"] },
  605: { name: "Elgyem", types: ["Psychic"] },
  606: { name: "Beheeyem", types: ["Psychic"] },
  607: { name: "Litwick", types: ["Ghost", "Fire"] },
  608: { name: "Lampent", types: ["Ghost", "Fire"] },
  609: { name: "Chandelure", types: ["Ghost", "Fire"] },
  610: { name: "Axew", types: ["Dragon"] },
  611: { name: "Fraxure", types: ["Dragon"] },
  612: { name: "Haxorus", types: ["Dragon"] },
  613: { name: "Cubchoo", types: ["Ice"] },
  614: { name: "Beartic", types: ["Ice"] },
  615: { name: "Cryogonal", types: ["Ice"] },
  616: { name: "Shelmet", types: ["Bug"] },
  617: { name: "Accelgor", types: ["Bug"] },
  618: { name: "Stunfisk", types: ["Ground", "Electric"] },
  619: { name: "Mienfoo", types: ["Fighting"] },
  620: { name: "Mienshao", types: ["Fighting"] },
  621: { name: "Druddigon", types: ["Dragon"] },
  622: { name: "Golett", types: ["Ground", "Ghost"] },
  623: { name: "Golurk", types: ["Ground", "Ghost"] },
  624: { name: "Pawniard", types: ["Dark", "Steel"] },
  625: { name: "Bisharp", types: ["Dark", "Steel"] },
  626: { name: "Bouffalant", types: ["Normal"] },
  627: { name: "Rufflet", types: ["Normal", "Flying"] },
  628: { name: "Braviary", types: ["Normal", "Flying"] },
  629: { name: "Vullaby", types: ["Dark", "Flying"] },
  630: { name: "Mandibuzz", types: ["Dark", "Flying"] },
  631: { name: "Heatmor", types: ["Fire"] },
  632: { name: "Durant", types: ["Bug", "Steel"] },
  633: { name: "Deino", types: ["Dark", "Dragon"] },
  634: { name: "Zweilous", types: ["Dark", "Dragon"] },
  635: { name: "Hydreigon", types: ["Dark", "Dragon"] },
  636: { name: "Larvesta", types: ["Bug", "Fire"] },
  637: { name: "Volcarona", types: ["Bug", "Fire"] },
  638: { name: "Cobalion", types: ["Steel", "Fighting"] },
  639: { name: "Terrakion", types: ["Rock", "Fighting"] },
  640: { name: "Virizion", types: ["Grass", "Fighting"] },
  641: { name: "Tornadus", types: ["Flying"] },
  642: { name: "Thundurus", types: ["Electric", "Flying"] },
  643: { name: "Reshiram", types: ["Dragon", "Fire"] },
  644: { name: "Zekrom", types: ["Dragon", "Electric"] },
  645: { name: "Landorus", types: ["Ground", "Flying"] },
  646: { name: "Kyurem", types: ["Dragon", "Ice"] },
  647: { name: "Keldeo", types: ["Water", "Fighting"] },
  648: { name: "Meloetta", types: ["Normal", "Psychic"] },
  649: { name: "Genesect", types: ["Bug", "Steel"] },
  650: { name: "Chespin", types: ["Grass"] },
  651: { name: "Quilladin", types: ["Grass"] },
  652: { name: "Chesnaught", types: ["Grass", "Fighting"] },
  653: { name: "Fennekin", types: ["Fire"] },
  654: { name: "Braixen", types: ["Fire"] },
  655: { name: "Delphox", types: ["Fire", "Psychic"] },
  656: { name: "Froakie", types: ["Water"] },
  657: { name: "Frogadier", types: ["Water"] },
  658: { name: "Greninja", types: ["Water", "Dark"] },
  659: { name: "Bunnelby", types: ["Normal"] },
  660: { name: "Diggersby", types: ["Normal", "Ground"] },
  661: { name: "Fletchling", types: ["Normal", "Flying"] },
  662: { name: "Fletchinder", types: ["Fire", "Flying"] },
  663: { name: "Talonflame", types: ["Fire", "Flying"] },
  664: { name: "Scatterbug", types: ["Bug"] },
  665: { name: "Spewpa", types: ["Bug"] },
  666: { name: "Vivillon", types: ["Bug", "Flying"] },
  667: { name: "Litleo", types: ["Fire", "Normal"] },
  668: { name: "Pyroar", types: ["Fire", "Normal"] },
  669: { name: "Flabébé", types: ["Fairy"] },
  670: { name: "Floette", types: ["Fairy"] },
  671: { name: "Florges", types: ["Fairy"] },
  672: { name: "Skiddo", types: ["Grass"] },
  673: { name: "Gogoat", types: ["Grass"] },
  674: { name: "Pancham", types: ["Fighting"] },
  675: { name: "Pangoro", types: ["Fighting", "Dark"] },
  676: { name: "Furfrou", types: ["Normal"] },
  677: { name: "Espurr", types: ["Psychic"] },
  678: { name: "Meowstic", types: ["Psychic"] },
  679: { name: "Honedge", types: ["Steel", "Ghost"] },
  680: { name: "Doublade", types: ["Steel", "Ghost"] },
  681: { name: "Aegislash", types: ["Steel", "Ghost"] },
  682: { name: "Spritzee", types: ["Fairy"] },
  683: { name: "Aromatisse", types: ["Fairy"] },
  684: { name: "Swirlix", types: ["Fairy"] },
  685: { name: "Slurpuff", types: ["Fairy"] },
  686: { name: "Inkay", types: ["Dark", "Psychic"] },
  687: { name: "Malamar", types: ["Dark", "Psychic"] },
  688: { name: "Binacle", types: ["Rock", "Water"] },
  689: { name: "Barbaracle", types: ["Rock", "Water"] },
  690: { name: "Skrelp", types: ["Poison", "Water"] },
  691: { name: "Dragalge", types: ["Poison", "Dragon"] },
  692: { name: "Clauncher", types: ["Water"] },
  693: { name: "Clawitzer", types: ["Water"] },
  694: { name: "Helioptile", types: ["Electric", "Normal"] },
  695: { name: "Heliolisk", types: ["Electric", "Normal"] },
  696: { name: "Tyrunt", types: ["Rock", "Dragon"] },
  697: { name: "Tyrantrum", types: ["Rock", "Dragon"] },
  698: { name: "Amaura", types: ["Rock", "Ice"] },
  699: { name: "Aurorus", types: ["Rock", "Ice"] },
  700: { name: "Sylveon", types: ["Fairy"] },
  701: { name: "Hawlucha", types: ["Fighting", "Flying"] },
  702: { name: "Dedenne", types: ["Electric", "Fairy"] },
  703: { name: "Carbink", types: ["Rock", "Fairy"] },
  704: { name: "Goomy", types: ["Dragon"] },
  705: { name: "Sliggoo", types: ["Dragon"] },
  706: { name: "Goodra", types: ["Dragon"] },
  707: { name: "Klefki", types: ["Steel", "Fairy"] },
  708: { name: "Phantump", types: ["Ghost", "Grass"] },
  709: { name: "Trevenant", types: ["Ghost", "Grass"] },
  710: { name: "Pumpkaboo", types: ["Ghost", "Grass"] },
  711: { name: "Gourgeist", types: ["Ghost", "Grass"] },
  712: { name: "Bergmite", types: ["Ice"] },
  713: { name: "Avalugg", types: ["Ice"] },
  714: { name: "Noibat", types: ["Flying", "Dragon"] },
  715: { name: "Noivern", types: ["Flying", "Dragon"] },
  716: { name: "Xerneas", types: ["Fairy"] },
  717: { name: "Yveltal", types: ["Dark", "Flying"] },
  718: { name: "Zygarde", types: ["Dragon", "Ground"] },
  719: { name: "Diancie", types: ["Rock", "Fairy"] },
  720: { name: "Hoopa", types: ["Psychic", "Ghost"] },
  721: { name: "Volcanion", types: ["Fire", "Water"] },
  722: { name: "Rowlet", types: ["Grass", "Flying"] },
  723: { name: "Dartrix", types: ["Grass", "Flying"] },
  724: { name: "Decidueye", types: ["Grass", "Ghost"] },
  725: { name: "Litten", types: ["Fire"] },
  726: { name: "Torracat", types: ["Fire"] },
  727: { name: "Incineroar", types: ["Fire", "Dark"] },
  728: { name: "Popplio", types: ["Water"] },
  729: { name: "Brionne", types: ["Water"] },
  730: { name: "Primarina", types: ["Water", "Fairy"] },
  731: { name: "Pikipek", types: ["Normal", "Flying"] },
  732: { name: "Trumbeak", types: ["Normal", "Flying"] },
  733: { name: "Toucannon", types: ["Normal", "Flying"] },
  734: { name: "Yungoos", types: ["Normal"] },
  735: { name: "Gumshoos", types: ["Normal"] },
  736: { name: "Grubbin", types: ["Bug"] },
  737: { name: "Charjabug", types: ["Bug", "Electric"] },
  738: { name: "Vikavolt", types: ["Bug", "Electric"] },
  739: { name: "Crabrawler", types: ["Fighting"] },
  740: { name: "Crabominable", types: ["Fighting", "Ice"] },
  741: { name: "Oricorio", types: ["Fire", "Flying"] },
  742: { name: "Cutiefly", types: ["Bug", "Fairy"] },
  743: { name: "Ribombee", types: ["Bug", "Fairy"] },
  744: { name: "Rockruff", types: ["Rock"] },
  745: { name: "Lycanroc", types: ["Rock"] },
  746: { name: "Wishiwashi", types: ["Water"] },
  747: { name: "Mareanie", types: ["Poison", "Water"] },
  748: { name: "Toxapex", types: ["Poison", "Water"] },
  749: { name: "Mudbray", types: ["Ground"] },
  750: { name: "Mudsdale", types: ["Ground"] },
  751: { name: "Dewpider", types: ["Water", "Bug"] },
  752: { name: "Araquanid", types: ["Water", "Bug"] },
  753: { name: "Fomantis", types: ["Grass"] },
  754: { name: "Lurantis", types: ["Grass"] },
  755: { name: "Morelull", types: ["Grass", "Fairy"] },
  756: { name: "Shiinotic", types: ["Grass", "Fairy"] },
  757: { name: "Salandit", types: ["Poison", "Fire"] },
  758: { name: "Salazzle", types: ["Poison", "Fire"] },
  759: { name: "Stufful", types: ["Normal", "Fighting"] },
  760: { name: "Bewear", types: ["Normal", "Fighting"] },
  761: { name: "Bounsweet", types: ["Grass"] },
  762: { name: "Steenee", types: ["Grass"] },
  763: { name: "Tsareena", types: ["Grass"] },
  764: { name: "Comfey", types: ["Fairy"] },
  765: { name: "Oranguru", types: ["Normal", "Psychic"] },
  766: { name: "Passimian", types: ["Fighting"] },
  767: { name: "Wimpod", types: ["Bug", "Water"] },
  768: { name: "Golisopod", types: ["Bug", "Water"] },
  769: { name: "Sandygast", types: ["Ghost", "Ground"] },
  770: { name: "Palossand", types: ["Ghost", "Ground"] },
  771: { name: "Pyukumuku", types: ["Water"] },
  772: { name: "Type: Null", types: ["Normal"] },
  773: { name: "Silvally", types: ["Normal"] },
  774: { name: "Minior", types: ["Rock", "Flying"] },
  775: { name: "Komala", types: ["Normal"] },
  776: { name: "Turtonator", types: ["Fire", "Dragon"] },
  777: { name: "Togedemaru", types: ["Electric", "Steel"] },
  778: { name: "Mimikyu", types: ["Ghost", "Fairy"] },
  779: { name: "Bruxish", types: ["Water", "Psychic"] },
  780: { name: "Drampa", types: ["Normal", "Dragon"] },
  781: { name: "Dhelmise", types: ["Ghost", "Grass"] },
  782: { name: "Jangmo-o", types: ["Dragon"] },
  783: { name: "Hakamo-o", types: ["Dragon", "Fighting"] },
  784: { name: "Kommo-o", types: ["Dragon", "Fighting"] },
  785: { name: "Tapu Koko", types: ["Electric", "Fairy"] },
  786: { name: "Tapu Lele", types: ["Psychic", "Fairy"] },
  787: { name: "Tapu Bulu", types: ["Grass", "Fairy"] },
  788: { name: "Tapu Fini", types: ["Water", "Fairy"] },
  789: { name: "Cosmog", types: ["Psychic"] },
  790: { name: "Cosmoem", types: ["Psychic"] },
  791: { name: "Solgaleo", types: ["Psychic", "Steel"] },
  792: { name: "Lunala", types: ["Psychic", "Ghost"] },
  793: { name: "Nihilego", types: ["Rock", "Poison"] },
  794: { name: "Buzzwole", types: ["Bug", "Fighting"] },
  795: { name: "Pheromosa", types: ["Bug", "Fighting"] },
  796: { name: "Xurkitree", types: ["Electric"] },
  797: { name: "Celesteela", types: ["Steel", "Flying"] },
  798: { name: "Kartana", types: ["Grass", "Steel"] },
  799: { name: "Guzzlord", types: ["Dark", "Dragon"] },
  800: { name: "Necrozma", types: ["Psychic"] },
  801: { name: "Magearna", types: ["Steel", "Fairy"] },
  802: { name: "Marshadow", types: ["Fighting", "Ghost"] },
  803: { name: "Poipole", types: ["Poison"] },
  804: { name: "Naganadel", types: ["Poison", "Dragon"] },
  805: { name: "Stakataka", types: ["Rock", "Steel"] },
  806: { name: "Blacephalon", types: ["Fire", "Ghost"] },
  807: { name: "Zeraora", types: ["Electric"] },
  808: { name: "Meltan", types: ["Steel"] },
  809: { name: "Melmetal", types: ["Steel"] },
  810: { name: "Grookey", types: ["Grass"] },
  811: { name: "Thwackey", types: ["Grass"] },
  812: { name: "Rillaboom", types: ["Grass"] },
  813: { name: "Scorbunny", types: ["Fire"] },
  814: { name: "Raboot", types: ["Fire"] },
  815: { name: "Cinderace", types: ["Fire"] },
  816: { name: "Sobble", types: ["Water"] },
  817: { name: "Drizzile", types: ["Water"] },
  818: { name: "Inteleon", types: ["Water"] },
  819: { name: "Skwovet", types: ["Normal"] },
  820: { name: "Greedent", types: ["Normal"] },
  821: { name: "Rookidee", types: ["Flying"] },
  822: { name: "Corvisquire", types: ["Flying"] },
  823: { name: "Corviknight", types: ["Flying", "Steel"] },
  824: { name: "Blipbug", types: ["Bug"] },
  825: { name: "Dottler", types: ["Bug", "Psychic"] },
  826: { name: "Orbeetle", types: ["Bug", "Psychic"] },
  827: { name: "Nickit", types: ["Dark"] },
  828: { name: "Thievul", types: ["Dark"] },
  829: { name: "Gossifleur", types: ["Grass"] },
  830: { name: "Eldegoss", types: ["Grass"] },
  831: { name: "Wooloo", types: ["Normal"] },
  832: { name: "Dubwool", types: ["Normal"] },
  833: { name: "Chewtle", types: ["Water"] },
  834: { name: "Drednaw", types: ["Water", "Rock"] },
  835: { name: "Yamper", types: ["Electric"] },
  836: { name: "Boltund", types: ["Electric"] },
  837: { name: "Rolycoly", types: ["Rock"] },
  838: { name: "Carkol", types: ["Rock", "Fire"] },
  839: { name: "Coalossal", types: ["Rock", "Fire"] },
  840: { name: "Applin", types: ["Grass", "Dragon"] },
  841: { name: "Flapple", types: ["Grass", "Dragon"] },
  842: { name: "Appletun", types: ["Grass", "Dragon"] },
  843: { name: "Silicobra", types: ["Ground"] },
  844: { name: "Sandaconda", types: ["Ground"] },
  845: { name: "Cramorant", types: ["Flying", "Water"] },
  846: { name: "Arrokuda", types: ["Water"] },
  847: { name: "Barraskewda", types: ["Water"] },
  848: { name: "Toxel", types: ["Electric", "Poison"] },
  849: { name: "Toxtricity", types: ["Electric", "Poison"] },
  850: { name: "Sizzlipede", types: ["Fire", "Bug"] },
  851: { name: "Centiskorch", types: ["Fire", "Bug"] },
  852: { name: "Clobbopus", types: ["Fighting"] },
  853: { name: "Grapploct", types: ["Fighting"] },
  854: { name: "Sinistea", types: ["Ghost"] },
  855: { name: "Polteageist", types: ["Ghost"] },
  856: { name: "Hatenna", types: ["Psychic"] },
  857: { name: "Hattrem", types: ["Psychic"] },
  858: { name: "Hatterene", types: ["Psychic", "Fairy"] },
  859: { name: "Impidimp", types: ["Dark", "Fairy"] },
  860: { name: "Morgrem", types: ["Dark", "Fairy"] },
  861: { name: "Grimmsnarl", types: ["Dark", "Fairy"] },
  862: { name: "Obstagoon", types: ["Dark", "Normal"] },
  863: { name: "Perrserker", types: ["Steel"] },
  864: { name: "Cursola", types: ["Ghost"] },
  865: { name: "Sirfetch’d", types: ["Fighting"] },
  866: { name: "Mr. Rime", types: ["Ice", "Psychic"] },
  867: { name: "Runerigus", types: ["Ground", "Ghost"] },
  868: { name: "Milcery", types: ["Fairy"] },
  869: { name: "Alcremie", types: ["Fairy"] },
  870: { name: "Falinks", types: ["Fighting"] },
  871: { name: "Pincurchin", types: ["Electric"] },
  872: { name: "Snom", types: ["Ice", "Bug"] },
  873: { name: "Frosmoth", types: ["Ice", "Bug"] },
  874: { name: "Stonjourner", types: ["Rock"] },
  875: { name: "Eiscue", types: ["Ice"] },
  876: { name: "Indeedee", types: ["Psychic", "Normal"] },
  877: { name: "Morpeko", types: ["Electric", "Dark"] },
  878: { name: "Cufant", types: ["Steel"] },
  879: { name: "Copperajah", types: ["Steel"] },
  880: { name: "Dracozolt", types: ["Electric", "Dragon"] },
  881: { name: "Arctozolt", types: ["Electric", "Ice"] },
  882: { name: "Dracovish", types: ["Water", "Dragon"] },
  883: { name: "Arctovish", types: ["Water", "Ice"] },
  884: { name: "Duraludon", types: ["Steel", "Dragon"] },
  885: { name: "Dreepy", types: ["Dragon", "Ghost"] },
  886: { name: "Drakloak", types: ["Dragon", "Ghost"] },
  887: { name: "Dragapult", types: ["Dragon", "Ghost"] },
  888: { name: "Zacian", types: ["Fairy"] },
  889: { name: "Zamazenta", types: ["Fighting"] },
  890: { name: "Eternatus", types: ["Poison", "Dragon"] },
  891: { name: "Kubfu", types: ["Fighting"] },
  892: { name: "Urshifu", types: ["Fighting", "Dark"] },
  893: { name: "Zarude", types: ["Dark", "Grass"] },
  894: { name: "Regieleki", types: ["Electric"] },
  895: { name: "Regidrago", types: ["Dragon"] },
  896: { name: "Glastrier", types: ["Ice"] },
  897: { name: "Spectrier", types: ["Ghost"] },
  898: { name: "Calyrex", types: ["Psychic", "Grass"] },
  899: { name: "Wyrdeer", types: ["Normal", "Psychic"] },
  900: { name: "Kleavor", types: ["Bug", "Rock"] },
  901: { name: "Ursaluna", types: ["Ground", "Normal"] },
  902: { name: "Basculegion", types: ["Water", "Ghost"] },
  903: { name: "Sneasler", types: ["Fighting", "Poison"] },
  904: { name: "Overqwil", types: ["Dark", "Poison"] },
  905: { name: "Enamorus", types: ["Fairy", "Flying"] },
  906: { name: "Sprigatito", types: ["Grass"] },
  907: { name: "Floragato", types: ["Grass"] },
  908: { name: "Meowscarada", types: ["Grass", "Dark"] },
  909: { name: "Fuecoco", types: ["Fire"] },
  910: { name: "Crocalor", types: ["Fire"] },
  911: { name: "Skeledirge", types: ["Fire", "Ghost"] },
  912: { name: "Quaxly", types: ["Water"] },
  913: { name: "Quaxwell", types: ["Water"] },
  914: { name: "Quaquaval", types: ["Water", "Fighting"] },
  915: { name: "Lechonk", types: ["Normal"] },
  916: { name: "Oinkologne", types: ["Normal"] },
  917: { name: "Tarountula", types: ["Bug"] },
  918: { name: "Spidops", types: ["Bug"] },
  919: { name: "Nymble", types: ["Bug"] },
  920: { name: "Lokix", types: ["Bug", "Dark"] },
  921: { name: "Pawmi", types: ["Electric"] },
  922: { name: "Pawmo", types: ["Electric", "Fighting"] },
  923: { name: "Pawmot", types: ["Electric", "Fighting"] },
  924: { name: "Tandemaus", types: ["Normal"] },
  925: { name: "Maushold", types: ["Normal"] },
  926: { name: "Fidough", types: ["Fairy"] },
  927: { name: "Dachsbun", types: ["Fairy"] },
  928: { name: "Smoliv", types: ["Grass", "Normal"] },
  929: { name: "Dolliv", types: ["Grass", "Normal"] },
  930: { name: "Arboliva", types: ["Grass", "Normal"] },
  931: { name: "Squawkabilly", types: ["Normal", "Flying"] },
  932: { name: "Nacli", types: ["Rock"] },
  933: { name: "Naclstack", types: ["Rock"] },
  934: { name: "Garganacl", types: ["Rock"] },
  935: { name: "Charcadet", types: ["Fire"] },
  936: { name: "Armarouge", types: ["Fire", "Psychic"] },
  937: { name: "Ceruledge", types: ["Fire", "Ghost"] },
  938: { name: "Tadbulb", types: ["Electric"] },
  939: { name: "Bellibolt", types: ["Electric"] },
  940: { name: "Wattrel", types: ["Electric", "Flying"] },
  941: { name: "Kilowattrel", types: ["Electric", "Flying"] },
  942: { name: "Maschiff", types: ["Dark"] },
  943: { name: "Mabosstiff", types: ["Dark"] },
  944: { name: "Shroodle", types: ["Poison", "Normal"] },
  945: { name: "Grafaiai", types: ["Poison", "Normal"] },
  946: { name: "Bramblin", types: ["Grass", "Ghost"] },
  947: { name: "Brambleghast", types: ["Grass", "Ghost"] },
  948: { name: "Toedscool", types: ["Ground", "Grass"] },
  949: { name: "Toedscruel", types: ["Ground", "Grass"] },
  950: { name: "Klawf", types: ["Rock"] },
  951: { name: "Capsakid", types: ["Grass"] },
  952: { name: "Scovillain", types: ["Grass", "Fire"] },
  953: { name: "Rellor", types: ["Bug"] },
  954: { name: "Rabsca", types: ["Bug", "Psychic"] },
  955: { name: "Flittle", types: ["Psychic"] },
  956: { name: "Espathra", types: ["Psychic"] },
  957: { name: "Tinkatink", types: ["Fairy", "Steel"] },
  958: { name: "Tinkatuff", types: ["Fairy", "Steel"] },
  959: { name: "Tinkaton", types: ["Fairy", "Steel"] },
  960: { name: "Wiglett", types: ["Water"] },
  961: { name: "Wugtrio", types: ["Water"] },
  962: { name: "Bombirdier", types: ["Flying", "Dark"] },
  963: { name: "Finizen", types: ["Water"] },
  964: { name: "Palafin", types: ["Water"] },
  965: { name: "Varoom", types: ["Steel", "Poison"] },
  966: { name: "Revavroom", types: ["Steel", "Poison"] },
  967: { name: "Cyclizar", types: ["Dragon", "Normal"] },
  968: { name: "Orthworm", types: ["Steel"] },
  969: { name: "Glimmet", types: ["Rock", "Poison"] },
  970: { name: "Glimmora", types: ["Rock", "Poison"] },
  971: { name: "Greavard", types: ["Ghost"] },
  972: { name: "Houndstone", types: ["Ghost"] },
  973: { name: "Flamigo", types: ["Flying", "Fighting"] },
  974: { name: "Cetoddle", types: ["Ice"] },
  975: { name: "Cetitan", types: ["Ice"] },
  976: { name: "Veluza", types: ["Water", "Psychic"] },
  977: { name: "Dondozo", types: ["Water"] },
  978: { name: "Tatsugiri", types: ["Dragon", "Water"] },
  979: { name: "Annihilape", types: ["Fighting", "Ghost"] },
  980: { name: "Clodsire", types: ["Poison", "Ground"] },
  981: { name: "Farigiraf", types: ["Normal", "Psychic"] },
  982: { name: "Dudunsparce", types: ["Normal"] },
  983: { name: "Kingambit", types: ["Dark", "Steel"] },
  984: { name: "Great Tusk", types: ["Ground", "Fighting"] },
  985: { name: "Scream Tail", types: ["Fairy", "Psychic"] },
  986: { name: "Brute Bonnet", types: ["Grass", "Dark"] },
  987: { name: "Flutter Mane", types: ["Ghost", "Fairy"] },
  988: { name: "Slither Wing", types: ["Bug", "Fighting"] },
  989: { name: "Sandy Shocks", types: ["Electric", "Ground"] },
  990: { name: "Iron Treads", types: ["Ground", "Steel"] },
  991: { name: "Iron Bundle", types: ["Ice", "Water"] },
  992: { name: "Iron Hands", types: ["Fighting", "Electric"] },
  993: { name: "Iron Jugulis", types: ["Dark", "Flying"] },
  994: { name: "Iron Moth", types: ["Fire", "Poison"] },
  995: { name: "Iron Thorns", types: ["Rock", "Electric"] },
  996: { name: "Frigibax", types: ["Dragon", "Ice"] },
  997: { name: "Arctibax", types: ["Dragon", "Ice"] },
  998: { name: "Baxcalibur", types: ["Dragon", "Ice"] },
  999: { name: "Gimmighoul", types: ["Ghost"] },
  1000: { name: "Gholdengo", types: ["Steel", "Ghost"] },
  1001: { name: "Wo-Chien", types: ["Dark", "Grass"] },
  1002: { name: "Chien-Pao", types: ["Dark", "Ice"] },
  1003: { name: "Ting-Lu", types: ["Dark", "Ground"] },
  1004: { name: "Chi-Yu", types: ["Dark", "Fire"] },
  1005: { name: "Roaring Moon", types: ["Dragon", "Dark"] },
  1006: { name: "Iron Valiant", types: ["Fairy", "Fighting"] },
  1007: { name: "Koraidon", types: ["Fighting", "Dragon"] },
  1008: { name: "Miraidon", types: ["Electric", "Dragon"] },
  1009: { name: "Walking Wake", types: ["Water", "Dragon"] },
  1010: { name: "Iron Leaves", types: ["Grass", "Psychic"] },
  1011: { name: "Dipplin", types: ["Grass", "Dragon"] },
  1012: { name: "Poltchageist", types: ["Grass", "Ghost"] },
  1013: { name: "Sinistcha", types: ["Grass", "Ghost"] },
  1014: { name: "Okidogi", types: ["Poison", "Fighting"] },
  1015: { name: "Munkidori", types: ["Poison", "Psychic"] },
  1016: { name: "Fezandipiti", types: ["Poison", "Fairy"] },
  1017: { name: "Ogerpon", types: ["Grass"] },
  1018: { name: "Archaludon", types: ["Steel", "Dragon"] },
  1019: { name: "Hydrapple", types: ["Grass", "Dragon"] },
  1020: { name: "Gouging Fire", types: ["Fire", "Dragon"] },
  1021: { name: "Raging Bolt", types: ["Electric", "Dragon"] },
  1022: { name: "Iron Boulder", types: ["Rock", "Psychic"] },
  1023: { name: "Iron Crown", types: ["Steel", "Psychic"] },
  1024: { name: "Terapagos", types: ["Normal"] },
  1025: { name: "Pecharunt", types: ["Poison", "Ghost"] }
};

const REGIONAL_FORMS = [
  { id: 10091, species: 19, name: "Alolan Rattata", region: "Alola", types: ["Dark", "Normal"] },
  { id: 10092, species: 20, name: "Alolan Raticate", region: "Alola", types: ["Dark", "Normal"] },
  { id: 10100, species: 26, name: "Alolan Raichu", region: "Alola", types: ["Electric", "Psychic"] },
  { id: 10101, species: 27, name: "Alolan Sandshrew", region: "Alola", types: ["Ice", "Steel"] },
  { id: 10102, species: 28, name: "Alolan Sandslash", region: "Alola", types: ["Ice", "Steel"] },
  { id: 10103, species: 37, name: "Alolan Vulpix", region: "Alola", types: ["Ice"] },
  { id: 10104, species: 38, name: "Alolan Ninetales", region: "Alola", types: ["Ice", "Fairy"] },
  { id: 10105, species: 50, name: "Alolan Diglett", region: "Alola", types: ["Ground", "Steel"] },
  { id: 10106, species: 51, name: "Alolan Dugtrio", region: "Alola", types: ["Ground", "Steel"] },
  { id: 10107, species: 52, name: "Alolan Meowth", region: "Alola", types: ["Dark"] },
  { id: 10108, species: 53, name: "Alolan Persian", region: "Alola", types: ["Dark"] },
  { id: 10109, species: 74, name: "Alolan Geodude", region: "Alola", types: ["Rock", "Electric"] },
  { id: 10110, species: 75, name: "Alolan Graveler", region: "Alola", types: ["Rock", "Electric"] },
  { id: 10111, species: 76, name: "Alolan Golem", region: "Alola", types: ["Rock", "Electric"] },
  { id: 10112, species: 88, name: "Alolan Grimer", region: "Alola", types: ["Poison", "Dark"] },
  { id: 10113, species: 89, name: "Alolan Muk", region: "Alola", types: ["Poison", "Dark"] },
  { id: 10114, species: 103, name: "Alolan Exeggutor", region: "Alola", types: ["Grass", "Dragon"] },
  { id: 10115, species: 105, name: "Alolan Marowak", region: "Alola", types: ["Fire", "Ghost"] },
  { id: 10161, species: 52, name: "Galarian Meowth", region: "Galar", types: ["Steel"] },
  { id: 10162, species: 77, name: "Galarian Ponyta", region: "Galar", types: ["Psychic"] },
  { id: 10163, species: 78, name: "Galarian Rapidash", region: "Galar", types: ["Psychic", "Fairy"] },
  { id: 10164, species: 79, name: "Galarian Slowpoke", region: "Galar", types: ["Psychic"] },
  { id: 10165, species: 80, name: "Galarian Slowbro", region: "Galar", types: ["Poison", "Psychic"] },
  { id: 10166, species: 83, name: "Galarian Farfetch’d", region: "Galar", types: ["Fighting"] },
  { id: 10167, species: 110, name: "Galarian Weezing", region: "Galar", types: ["Poison", "Fairy"] },
  { id: 10168, species: 122, name: "Galarian Mr. Mime", region: "Galar", types: ["Ice", "Psychic"] },
  { id: 10169, species: 144, name: "Galarian Articuno", region: "Galar", types: ["Psychic", "Flying"] },
  { id: 10170, species: 145, name: "Galarian Zapdos", region: "Galar", types: ["Fighting", "Flying"] },
  { id: 10171, species: 146, name: "Galarian Moltres", region: "Galar", types: ["Dark", "Flying"] },
  { id: 10172, species: 199, name: "Galarian Slowking", region: "Galar", types: ["Poison", "Psychic"] },
  { id: 10173, species: 222, name: "Galarian Corsola", region: "Galar", types: ["Ghost"] },
  { id: 10174, species: 263, name: "Galarian Zigzagoon", region: "Galar", types: ["Dark", "Normal"] },
  { id: 10175, species: 264, name: "Galarian Linoone", region: "Galar", types: ["Dark", "Normal"] },
  { id: 10176, species: 554, name: "Galarian Darumaka", region: "Galar", types: ["Ice"] },
  { id: 10177, species: 555, name: "Galarian Darmanitan", region: "Galar", types: ["Ice"] },
  { id: 10179, species: 562, name: "Galarian Yamask", region: "Galar", types: ["Ground", "Ghost"] },
  { id: 10180, species: 618, name: "Galarian Stunfisk", region: "Galar", types: ["Ground", "Steel"] },
  { id: 10229, species: 58, name: "Hisuian Growlithe", region: "Hisui", types: ["Fire", "Rock"] },
  { id: 10230, species: 59, name: "Hisuian Arcanine", region: "Hisui", types: ["Fire", "Rock"] },
  { id: 10231, species: 100, name: "Hisuian Voltorb", region: "Hisui", types: ["Electric", "Grass"] },
  { id: 10232, species: 101, name: "Hisuian Electrode", region: "Hisui", types: ["Electric", "Grass"] },
  { id: 10233, species: 157, name: "Hisuian Typhlosion", region: "Hisui", types: ["Fire", "Ghost"] },
  { id: 10234, species: 211, name: "Hisuian Qwilfish", region: "Hisui", types: ["Dark", "Poison"] },
  { id: 10235, species: 215, name: "Hisuian Sneasel", region: "Hisui", types: ["Fighting", "Poison"] },
  { id: 10236, species: 503, name: "Hisuian Samurott", region: "Hisui", types: ["Water", "Dark"] },
  { id: 10237, species: 549, name: "Hisuian Lilligant", region: "Hisui", types: ["Grass", "Fighting"] },
  { id: 10238, species: 570, name: "Hisuian Zorua", region: "Hisui", types: ["Normal", "Ghost"] },
  { id: 10239, species: 571, name: "Hisuian Zoroark", region: "Hisui", types: ["Normal", "Ghost"] },
  { id: 10240, species: 628, name: "Hisuian Braviary", region: "Hisui", types: ["Psychic", "Flying"] },
  { id: 10241, species: 705, name: "Hisuian Sliggoo", region: "Hisui", types: ["Steel", "Dragon"] },
  { id: 10242, species: 706, name: "Hisuian Goodra", region: "Hisui", types: ["Steel", "Dragon"] },
  { id: 10243, species: 713, name: "Hisuian Avalugg", region: "Hisui", types: ["Ice", "Rock"] },
  { id: 10244, species: 724, name: "Hisuian Decidueye", region: "Hisui", types: ["Grass", "Fighting"] },
  { id: 10250, species: 128, name: "Paldean Tauros (Combat Breed)", region: "Paldea", types: ["Fighting"] },
  { id: 10251, species: 128, name: "Paldean Tauros (Blaze Breed)", region: "Paldea", types: ["Fighting", "Fire"] },
  { id: 10252, species: 128, name: "Paldean Tauros (Aqua Breed)", region: "Paldea", types: ["Fighting", "Water"] },
  { id: 10253, species: 194, name: "Paldean Wooper", region: "Paldea", types: ["Poison", "Ground"] }
];

// Generate list of 1025 Pokemon (+ regional forms right after their base species)
const FORM_GEN = { Alola: "Gen 7", Galar: "Gen 8", Hisui: "Gen 8", Paldea: "Gen 9" };
const spriteUrls = (id) => ({
  sprite: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`,
  artwork: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`,
  shiny_sprite: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/${id}.png`,
  shiny_artwork: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/${id}.png`
});

const db = [];
for (let i = 1; i <= 1025; i++) {
  const info = getGenInfo(i);
  const known = KNOWN_POKEMON[i] || {};
  const name = known.name || `Pokémon #${i}`;
  const types = known.types || ["Normal"];

  db.push({
    id: i,
    dexNumber: i,
    name: name,
    types: types,
    gen: info.gen,
    region: info.region,
    ...spriteUrls(i)
  });

  REGIONAL_FORMS.filter(f => f.species === i).forEach(f => {
    db.push({
      id: f.id,
      dexNumber: i,
      name: f.name,
      form: f.region,
      types: f.types,
      gen: info.gen,
      formGen: FORM_GEN[f.region],
      region: f.region,
      ...spriteUrls(f.id)
    });
  });
}

window.POKEMON_DATABASE = db;
